#!/bin/bash

export KERNELNAME=StiFF 大都 #UNubSarGang

export LOCALVERSION=@paokzzz

export KBUILD_BUILD_USER=StiFF 大都 

export KBUILD_BUILD_HOST=paokzzz

export TOOLCHAIN=clang

export DEVICES=whyred

source helper

gen_toolchain

send_msg "Start building..."

START=$(date +"%s")

for i in ${DEVICES//,/ }
do
	build_nonoc ${i} "oldcam"

	build_nonoc ${i} "newcam"
done

send_msg "Build OC..."
for i in ${DEVICES//,/ }
do
        build_oc ${i} "oldcam"

        build_oc ${i} "newcam"
done

END=$(date +"%s")

DIFF=$(( END - START ))

send_msg "Build complete in $((DIFF / 60))m $((DIFF % 60))s"

