#!/bin/bash

export KERNELNAME=StiFF 大都

export LOCALVERSION=V1

export KBUILD_BUILD_USER=StiFF 大都

export KBUILD_BUILD_HOST=StiFF 大都

export TOOLCHAIN=clang

export DEVICES=whyred

source helper

gen_toolchain

send_msg "Start building..."

START=$(date +"%s")

for i in ${DEVICES//,/ }
do
	build ${i} -oldcam

	build ${i} -newcam
done

send_msg "Build OC..."

git apply oc.patch

for i in ${DEVICES//,/ }
do
	if [ $i == "whyred" ] || [ $i == "tulip" ]
	then
		build ${i} -OC -oldcam

		build ${i} -OC -newcam
	fi
done

END=$(date +"%s")

DIFF=$(( END - START ))

send_msg "Build complete in $((DIFF / 60))m $((DIFF % 60))s"
